{
	"documenttitle": {
		"text": "Red Hat Security Advisory: python3 security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2023:0833"
		},
		"Status": "Final",
		"Version": "2",
		"revisionhistory": {
			"revision": {
				"Number": "2",
				"Date": "2023-02-21T11:33:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2023-02-21T11:33:00Z",
		"CurrentReleaseDate": "2023-02-21T11:33:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.11.0",
			"Date": "2023-02-21T18:45:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for python3 is now available for Red Hat Enterprise Linux 8.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nPython is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS (CVE-2020-10735)\n\n* python: open redirection vulnerability in lib/http/server.py may lead to information disclosure (CVE-2021-28861)\n\n* Python: CPU denial of service via inefficient IDNA decoder (CVE-2022-45061)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2023 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2023:0833",
				"Description": "https://access.redhat.com/errata/RHSA-2023:0833"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "A flaw was found in python. In algorithms with quadratic time complexity using non-binary bases, when using int(\"text\"), a system could take 50ms to parse an int string with 100,000 digits and 5s for 1,000,000 digits (float, decimal, int.from_bytes(), and int() for binary bases 2, 4, 8, 16, and 32 are not affected). The highest threat from this vulnerability is to system availability.",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-09-02T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2020-10735",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2023:0833"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2020-10735",
						"Description": "CVE-2020-10735"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1834423",
						"Description": "bz#1834423: CVE-2020-10735 python: int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2020-05-06T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1",
						"BaseOS-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "A vulnerability was found in python. This security flaw causes an open redirection vulnerability in lib/http/server.py due to no protection against multiple (/) at the beginning of the URI path. This issue may lead to information disclosure.",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-08-22T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-28861",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2023:0833"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-28861",
						"Description": "CVE-2021-28861"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2120642",
						"Description": "bz#2120642: CVE-2021-28861 python: open redirection vulnerability in lib/http/server.py may lead to information disclosure"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-08-23T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1",
						"BaseOS-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "A vulnerability was discovered in Python. A quadratic algorithm exists when processing inputs to the IDNA (RFC 3490) decoder, such that a crafted unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor, which could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied hostname.",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-45061",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2023:0833"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://github.com/python/cpython/issues/98433",
						"Description": "https://github.com/python/cpython/issues/98433"
					},
					{
						"URL": "https://python-security.readthedocs.io/vuln/slow-idna-large-strings.html",
						"Description": "https://python-security.readthedocs.io/vuln/slow-idna-large-strings.html"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-45061",
						"Description": "CVE-2022-45061"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2144072",
						"Description": "bz#2144072: CVE-2022-45061 Python: CPU denial of service via inefficient IDNA decoder"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-11-18T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1",
						"BaseOS-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat Enterprise Linux",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux AppStream (v. 8)",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux AppStream (v. 8)",
							"productid": "AppStream-8.7.0.Z.MAIN",
							"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux BaseOS (v. 8)",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux BaseOS (v. 8)",
							"productid": "BaseOS-8.7.0.Z.MAIN",
							"cpe": "cpe:/o:redhat:enterprise_linux:8::baseos"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python3-0:3.6.8-48.el8_7.1",
				"fullproductname": {
					"text": "python3-3.6.8-48.el8_7.1.src.rpm",
					"productid": "python3-0:3.6.8-48.el8_7.1",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python3-0:3.6.8-48.el8_7.1",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "AppStream-8.7.0.Z.MAIN",
				"fullproductname": {
					"text": "python3-0:3.6.8-48.el8_7.1 as a component of Red Hat Enterprise Linux AppStream (v. 8)",
					"productid": "AppStream-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
				}
			},
			{
				"productreference": "python3-0:3.6.8-48.el8_7.1",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "BaseOS-8.7.0.Z.MAIN",
				"fullproductname": {
					"text": "python3-0:3.6.8-48.el8_7.1 as a component of Red Hat Enterprise Linux BaseOS (v. 8)",
					"productid": "BaseOS-8.7.0.Z.MAIN:python3-0:3.6.8-48.el8_7.1",
					"cpe": "cpe:/o:redhat:enterprise_linux:8::baseos"
				}
			}
		]
	}
}
