{
	"documenttitle": {
		"text": "Red Hat Security Advisory: python security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2009:1178"
		},
		"Status": "Final",
		"Version": "2",
		"revisionhistory": {
			"revision": {
				"Number": "2",
				"Date": "2009-07-27T05:36:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2009-07-27T09:32:00Z",
		"CurrentReleaseDate": "2009-07-27T05:36:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.0.0",
			"Date": "2021-08-23T04:30:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nUpdated python packages that fix multiple security issues are now available\nfor Red Hat Enterprise Linux 3.\n\nThis update has been rated as having moderate security impact by the Red\nHat Security Response Team.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nPython is an interpreted, interactive, object-oriented programming\nlanguage.\n\nWhen the assert() system call was disabled, an input sanitization flaw was\nrevealed in the Python string object implementation that led to a buffer\noverflow. The missing check for negative size values meant the Python\nmemory allocator could allocate less memory than expected. This could\nresult in arbitrary code execution with the Python interpreter's\nprivileges. (CVE-2008-1887)\n\nMultiple buffer and integer overflow flaws were found in the Python Unicode\nstring processing and in the Python Unicode and string object\nimplementations. An attacker could use these flaws to cause a denial of\nservice (Python application crash). (CVE-2008-3142, CVE-2008-5031)\n\nMultiple integer overflow flaws were found in the Python imageop module. If\na Python application used the imageop module to process untrusted images,\nit could cause the application to crash or, potentially, execute arbitrary\ncode with the Python interpreter's privileges. (CVE-2008-1679,\nCVE-2008-4864)\n\nMultiple integer underflow and overflow flaws were found in the Python\nsnprintf() wrapper implementation. An attacker could use these flaws to\ncause a denial of service (memory corruption). (CVE-2008-3144)\n\nMultiple integer overflow flaws were found in various Python modules. An\nattacker could use these flaws to cause a denial of service (Python\napplication crash). (CVE-2008-2315, CVE-2008-3143)\n\nRed Hat would like to thank David Remahl of the Apple Product Security team\nfor responsibly reporting the CVE-2008-1679 and CVE-2008-2315 issues.\n\nAll Python users should upgrade to these updated packages, which contain\nbackported patches to correct these issues.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2021 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2009:1178",
				"Description": "https://access.redhat.com/errata/RHSA-2009:1178"
			},
			{
				"type": "External",
				"URL": "http://www.redhat.com/security/updates/classification/#moderate",
				"Description": "http://www.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: imageop module integer overflows",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-03-29T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-1679",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-1679",
						"Description": "CVE-2008-1679"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=441306",
						"Description": "bz#441306: CVE-2008-1679 python: imageop module integer overflows"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-04-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: PyString_FromStringAndSize does not check for negative size values",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-04-08T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-1887",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-1887",
						"Description": "CVE-2008-1887"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=443810",
						"Description": "bz#443810: CVE-2008-1887 python: PyString_FromStringAndSize does not check for negative size values"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2008-04-18T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Multiple integer overflows in python core",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-07-31T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-2315",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-2315",
						"Description": "CVE-2008-2315"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=455008",
						"Description": "bz#455008: CVE-2008-2315 python: Multiple integer overflows in python core"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-07-02T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "4",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Multiple buffer overflows in unicode processing",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-04-11T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-3142",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-3142",
						"Description": "CVE-2008-3142"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=454990",
						"Description": "bz#454990: CVE-2008-3142 python: Multiple buffer overflows in unicode processing"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-07-02T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "5",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Multiple integer overflows discovered by Google",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-02-14T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-3143",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-3143",
						"Description": "CVE-2008-3143"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=455013",
						"Description": "bz#455013: CVE-2008-3143 python: Multiple integer overflows discovered by Google"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-07-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "6",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-06-02T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-3144",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-3144",
						"Description": "CVE-2008-3144"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=455018",
						"Description": "bz#455018: CVE-2008-3144 python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-07-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "7",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: imageop module multiple integer overflows",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-10-19T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-4864",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-4864",
						"Description": "CVE-2008-4864"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=469656",
						"Description": "bz#469656: CVE-2008-4864 python: imageop module multiple integer overflows"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-10-19T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "8",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: stringobject, unicodeobject integer overflows",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2008-10-19T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2008-5031",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure that all previously-released\nerrata relevant to your system have been applied.\n\nThis update is available via Red Hat Network.  Details on how to use\nthe Red Hat Network to apply this update are available at\nhttp://kbase.redhat.com/faq/docs/DOC-11259\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2009:1178"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2008-5031",
						"Description": "CVE-2008-5031"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=470915",
						"Description": "bz#470915: CVE-2008-5031 python: stringobject, unicodeobject integer overflows"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2008-10-19T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"3AS:python-0:2.2.3-6.11",
						"3Desktop:python-0:2.2.3-6.11",
						"3ES:python-0:2.2.3-6.11",
						"3WS:python-0:2.2.3-6.11"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat Enterprise Linux",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux AS version 3",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux AS version 3",
							"productid": "3AS",
							"cpe": "cpe:/o:redhat:enterprise_linux:3::as"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat Desktop version 3",
						"fullproductname": {
							"text": "Red Hat Desktop version 3",
							"productid": "3Desktop",
							"cpe": "cpe:/o:redhat:enterprise_linux:3::desktop"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux ES version 3",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux ES version 3",
							"productid": "3ES",
							"cpe": "cpe:/o:redhat:enterprise_linux:3::es"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux WS version 3",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux WS version 3",
							"productid": "3WS",
							"cpe": "cpe:/o:redhat:enterprise_linux:3::ws"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python-0:2.2.3-6.11",
				"fullproductname": {
					"text": "python-2.2.3-6.11.src.rpm",
					"productid": "python-0:2.2.3-6.11",
					"cpe": "cpe:/o:redhat:enterprise_linux:3::as"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python-0:2.2.3-6.11",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "3AS",
				"fullproductname": {
					"text": "python-0:2.2.3-6.11 as a component of Red Hat Enterprise Linux AS version 3",
					"productid": "3AS:python-0:2.2.3-6.11",
					"cpe": "cpe:/o:redhat:enterprise_linux:3::as"
				}
			},
			{
				"productreference": "python-0:2.2.3-6.11",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "3Desktop",
				"fullproductname": {
					"text": "python-0:2.2.3-6.11 as a component of Red Hat Desktop version 3",
					"productid": "3Desktop:python-0:2.2.3-6.11",
					"cpe": "cpe:/o:redhat:enterprise_linux:3::desktop"
				}
			},
			{
				"productreference": "python-0:2.2.3-6.11",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "3ES",
				"fullproductname": {
					"text": "python-0:2.2.3-6.11 as a component of Red Hat Enterprise Linux ES version 3",
					"productid": "3ES:python-0:2.2.3-6.11",
					"cpe": "cpe:/o:redhat:enterprise_linux:3::es"
				}
			},
			{
				"productreference": "python-0:2.2.3-6.11",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "3WS",
				"fullproductname": {
					"text": "python-0:2.2.3-6.11 as a component of Red Hat Enterprise Linux WS version 3",
					"productid": "3WS:python-0:2.2.3-6.11",
					"cpe": "cpe:/o:redhat:enterprise_linux:3::ws"
				}
			}
		]
	}
}
