{
	"documenttitle": {
		"text": "Red Hat Security Advisory: galera, mariadb, and mysql-selinux security, bug fix, and enhancement update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2022:5948"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2022-11-16T12:17:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2022-08-09T12:23:00Z",
		"CurrentReleaseDate": "2022-11-16T12:17:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.9.4",
			"Date": "2022-11-16T12:56:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for galera, mariadb, and mysql-selinux is now available for Red Hat Enterprise Linux 9.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nMariaDB is a multi-user, multi-threaded SQL database server that is binary compatible with MySQL. \n\nThe following packages have been upgraded to a later upstream version: galera (26.4.11), mariadb (10.5.16), mysql-selinux (1.0.5).\n\nSecurity Fix(es):\n\n* mariadb: MariaDB through 10.5.9 allows attackers to trigger a convert_const_to_int use-after-free when the BIGINT data type is used (CVE-2021-46669)\n\n* mariadb: lack of proper validation of the length of user-supplied data prior to copying it to a fixed-length stack-based buffer (CVE-2022-24048)\n\n* mariadb: lack of validating the existence of an object prior to performing operations on the object (CVE-2022-24050)\n\n* mariadb: lack of proper validation of a user-supplied string before using it as a format specifier (CVE-2022-24051)\n\n* mariadb: CONNECT Storage Engine Heap-based Buffer Overflow Privilege Escalation Vulnerability (CVE-2022-24052)\n\n* mariadb: assertion failure in Item_args::walk_arg (CVE-2022-27376)\n\n* mariadb: use-after-poison when complex conversion is involved in blob (CVE-2022-27377)\n\n* mariadb: server crash in create_tmp_table::finalize (CVE-2022-27378)\n\n* mariadb: server crash in component arg_comparator::compare_real_fixed (CVE-2022-27379)\n\n* mariadb: server crash at my_decimal::operator= (CVE-2022-27380)\n\n* mariadb: server crash at Field::set_default via specially crafted SQL statements (CVE-2022-27381)\n\n* mariadb: assertion failure via component Item_field::used_tables/update_depend_map_for_order (CVE-2022-27382)\n\n* mariadb: use-after-poison in my_strcasecmp_8bit() of ctype-simple.c (CVE-2022-27383)\n\n* mariadb: crash via component Item_subselect::init_expr_cache_tracker (CVE-2022-27384)\n\n* mariadb: server crashes in query_arena::set_query_arena upon SELECT from view (CVE-2022-27386)\n\n* mariadb: assertion failures in decimal_bin_size (CVE-2022-27387)\n\n* mariadb: crash when using HAVING with NOT EXIST predicate in an equality (CVE-2022-27444)\n\n* mariadb: assertion failure in compare_order_elements (CVE-2022-27445)\n\n* mariadb: crash when using HAVING with IS NULL predicate in an equality (CVE-2022-27446)\n\n* mariadb: use-after-poison in Binary_string::free_buffer (CVE-2022-27447)\n\n* mariadb: crash in multi-update and implicit grouping (CVE-2022-27448)\n\n* mariadb: assertion failure in sql/item_func.cc (CVE-2022-27449)\n\n* mariadb: crash via window function in expression in ORDER BY (CVE-2022-27451)\n\n* mariadb: assertion failure in sql/item_cmpfunc.cc (CVE-2022-27452)\n\n* mariadb: use-after-free when WHERE has subquery with an outer reference in HAVING (CVE-2022-27455)\n\n* mariadb: assertion failure in VDec::VDec at /sql/sql_type.cc (CVE-2022-27456)\n\n* mariadb: incorrect key in \"dup value\" error after long unique (CVE-2022-27457)\n\n* mariadb: use-after-poison in Binary_string::free_buffer (CVE-2022-27458)\n\n* mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc (CVE-2022-31622)\n\n* mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc (CVE-2022-31623)\n\n* mariadb: Crash executing query with VIEW, aggregate and subquery (CVE-2021-46659)\n\n* mariadb: MariaDB allows an application crash in find_field_in_tables and find_order_in_list via an unused common table expression (CTE) (CVE-2021-46661)\n\n* mariadb: MariaDB through 10.5.13 allows a ha_maria::extra application crash via certain SELECT statements (CVE-2021-46663)\n\n* mariadb: MariaDB through 10.5.9 allows an application crash in sub_select_postjoin_aggr for a NULL value of aggr (CVE-2021-46664)\n\n* mariadb: MariaDB through 10.5.9 allows a sql_parse.cc application crash because of incorrect used_tables expectations (CVE-2021-46665)\n\n* mariadb: MariaDB through 10.5.9 allows an application crash via certain long SELECT DISTINCT statements (CVE-2021-46668)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2022 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2022:5948",
				"Description": "https://access.redhat.com/errata/RHSA-2022:5948"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: Crash executing query with VIEW, aggregate and subquery",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-10T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46659",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46659",
						"Description": "CVE-2021-46659"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2049302",
						"Description": "bz#2049302: CVE-2021-46659 mariadb: Crash executing query with VIEW, aggregate and subquery"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-01T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB allows an application crash in find_field_in_tables and find_order_in_list via an unused common table expression (CTE)",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-25T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46661",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46661",
						"Description": "CVE-2021-46661"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050017",
						"Description": "bz#2050017: CVE-2021-46661 mariadb: MariaDB allows an application crash in find_field_in_tables and find_order_in_list via an unused common table expression (CTE)"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB through 10.5.13 allows a ha_maria::extra application crash via certain SELECT statements",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-08-13T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46663",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46663",
						"Description": "CVE-2021-46663"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050022",
						"Description": "bz#2050022: CVE-2021-46663 mariadb: MariaDB through 10.5.13 allows a ha_maria::extra application crash via certain SELECT statements"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "4",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB through 10.5.9 allows an application crash in sub_select_postjoin_aggr for a NULL value of aggr",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-24T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46664",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46664",
						"Description": "CVE-2021-46664"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050024",
						"Description": "bz#2050024: CVE-2021-46664 mariadb: MariaDB through 10.5.9 allows an application crash in sub_select_postjoin_aggr for a NULL value of aggr"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "5",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB through 10.5.9 allows a sql_parse.cc application crash because of incorrect used_tables expectations",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-10T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46665",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46665",
						"Description": "CVE-2021-46665"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050026",
						"Description": "bz#2050026: CVE-2021-46665 mariadb: MariaDB through 10.5.9 allows a sql_parse.cc application crash because of incorrect used_tables expectations"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "6",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB through 10.5.9 allows an application crash via certain long SELECT DISTINCT statements",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-27T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46668",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46668",
						"Description": "CVE-2021-46668"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050032",
						"Description": "bz#2050032: CVE-2021-46668 mariadb: MariaDB through 10.5.9 allows an application crash via certain long SELECT DISTINCT statements"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "7",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: MariaDB through 10.5.9 allows attackers to trigger a convert_const_to_int use-after-free when the BIGINT data type is used",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-10T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-46669",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-46669",
						"Description": "CVE-2021-46669"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2050034",
						"Description": "bz#2050034: CVE-2021-46669 mariadb: MariaDB through 10.5.9 allows attackers to trigger a convert_const_to_int use-after-free when the BIGINT data type is used"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-02-03T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "8",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mysql: C API unspecified vulnerability (CPU Oct 2022)",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-10-18T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-21595",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-21595",
						"Description": "CVE-2022-21595"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2142862",
						"Description": "bz#2142862: CVE-2022-21595 mysql: C API unspecified vulnerability (CPU Oct 2022)"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-11-15T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "9",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: lack of proper validation of the length of user-supplied data prior to copying it to a fixed-length stack-based buffer",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-18T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-24048",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-24048",
						"Description": "CVE-2022-24048"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2068234",
						"Description": "bz#2068234: CVE-2022-24048 mariadb: lack of proper validation of the length of user-supplied data prior to copying it to a fixed-length stack-based buffer"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-03-24T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "10",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: lack of validating the existence of an object prior to performing operations on the object",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-18T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-24050",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-24050",
						"Description": "CVE-2022-24050"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2069833",
						"Description": "bz#2069833: CVE-2022-24050 mariadb: lack of validating the existence of an object prior to performing operations on the object"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-03-29T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "11",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: lack of proper validation of a user-supplied string before using it as a format specifier",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-18T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-24051",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-24051",
						"Description": "CVE-2022-24051"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2068233",
						"Description": "bz#2068233: CVE-2022-24051 mariadb: lack of proper validation of a user-supplied string before using it as a format specifier"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-03-24T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "12",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: CONNECT storage engine heap-based buffer overflow",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-18T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-24052",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://mariadb.com/kb/en/security/",
						"Description": "https://mariadb.com/kb/en/security/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-24052",
						"Description": "CVE-2022-24052"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2068211",
						"Description": "bz#2068211: CVE-2022-24052 mariadb: CONNECT storage engine heap-based buffer overflow"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-03-24T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "13",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure in Item_args::walk_arg",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27376",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27376",
						"Description": "CVE-2022-27376"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074817",
						"Description": "bz#2074817: CVE-2022-27376 mariadb: assertion failure in Item_args::walk_arg"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "14",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: use-after-poison when complex conversion is involved in blob",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-07-30T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27377",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27377",
						"Description": "CVE-2022-27377"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074947",
						"Description": "bz#2074947: CVE-2022-27377 mariadb: use-after-poison when complex conversion is involved in blob"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "15",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: server crash in create_tmp_table::finalize",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-08-19T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27378",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27378",
						"Description": "CVE-2022-27378"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074949",
						"Description": "bz#2074949: CVE-2022-27378 mariadb: server crash in create_tmp_table::finalize"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "16",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: server crash in component arg_comparator::compare_real_fixed",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-08-13T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27379",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27379",
						"Description": "CVE-2022-27379"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074951",
						"Description": "bz#2074951: CVE-2022-27379 mariadb: server crash in component arg_comparator::compare_real_fixed"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "17",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: server crash at my_decimal::operator=",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-06-23T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27380",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27380",
						"Description": "CVE-2022-27380"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074966",
						"Description": "bz#2074966: CVE-2022-27380 mariadb: server crash at my_decimal::operator="
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "18",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: server crash at Field::set_default via specially crafted SQL statements",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-07-01T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27381",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27381",
						"Description": "CVE-2022-27381"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074981",
						"Description": "bz#2074981: CVE-2022-27381 mariadb: server crash at Field::set_default via specially crafted SQL statements"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "19",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure via component Item_field::used_tables/update_depend_map_for_order",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-08-19T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27382",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27382",
						"Description": "CVE-2022-27382"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074987",
						"Description": "bz#2074987: CVE-2022-27382 mariadb: assertion failure via component Item_field::used_tables/update_depend_map_for_order"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "20",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: use-after-poison in my_strcasecmp_8bit() of ctype-simple.c",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-08-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27383",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27383",
						"Description": "CVE-2022-27383"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074996",
						"Description": "bz#2074996: CVE-2022-27383 mariadb: use-after-poison in my_strcasecmp_8bit() of ctype-simple.c"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "21",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: crash via component Item_subselect::init_expr_cache_tracker",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-06-30T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27384",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27384",
						"Description": "CVE-2022-27384"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2074999",
						"Description": "bz#2074999: CVE-2022-27384 mariadb: crash via component Item_subselect::init_expr_cache_tracker"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "22",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: server crashes in query_arena::set_query_arena upon SELECT from view",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-11-11T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27386",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27386",
						"Description": "CVE-2022-27386"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075005",
						"Description": "bz#2075005: CVE-2022-27386 mariadb: server crashes in query_arena::set_query_arena upon SELECT from view"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "23",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failures in decimal_bin_size",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-01T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27387",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27387",
						"Description": "CVE-2022-27387"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075006",
						"Description": "bz#2075006: CVE-2022-27387 mariadb: assertion failures in decimal_bin_size"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "24",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: crash when using HAVING with NOT EXIST predicate in an equality",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27444",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27444",
						"Description": "CVE-2022-27444"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075696",
						"Description": "bz#2075696: CVE-2022-27444 mariadb: crash when using HAVING with NOT EXIST predicate in an equality"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "25",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure in compare_order_elements",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-05-06T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27445",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27445",
						"Description": "CVE-2022-27445"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075691",
						"Description": "bz#2075691: CVE-2022-27445 mariadb: assertion failure in compare_order_elements"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "26",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: crash when using HAVING with IS NULL predicate in an equality",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27446",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27446",
						"Description": "CVE-2022-27446"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075692",
						"Description": "bz#2075692: CVE-2022-27446 mariadb: crash when using HAVING with IS NULL predicate in an equality"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "27",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: use-after-poison in Binary_string::free_buffer",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27447",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27447",
						"Description": "CVE-2022-27447"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075693",
						"Description": "bz#2075693: CVE-2022-27447 mariadb: use-after-poison in Binary_string::free_buffer"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "28",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: crash in multi-update and implicit grouping",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27448",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27448",
						"Description": "CVE-2022-27448"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075694",
						"Description": "bz#2075694: CVE-2022-27448 mariadb: crash in multi-update and implicit grouping"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "29",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure in sql/item_func.cc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27449",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27449",
						"Description": "CVE-2022-27449"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075695",
						"Description": "bz#2075695: CVE-2022-27449 mariadb: assertion failure in sql/item_func.cc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "30",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: crash via window function in expression in ORDER BY",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27451",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27451",
						"Description": "CVE-2022-27451"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2076144",
						"Description": "bz#2076144: CVE-2022-27451 mariadb: crash via window function in expression in ORDER BY"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-18T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "31",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure in sql/item_cmpfunc.cc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27452",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27452",
						"Description": "CVE-2022-27452"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2076145",
						"Description": "bz#2076145: CVE-2022-27452 mariadb: assertion failure in sql/item_cmpfunc.cc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-18T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "32",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: use-after-free when WHERE has subquery with an outer reference in HAVING",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27455",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27455",
						"Description": "CVE-2022-27455"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075701",
						"Description": "bz#2075701: CVE-2022-27455 mariadb: use-after-free when WHERE has subquery with an outer reference in HAVING"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "33",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: assertion failure in VDec::VDec at /sql/sql_type.cc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27456",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27456",
						"Description": "CVE-2022-27456"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075697",
						"Description": "bz#2075697: CVE-2022-27456 mariadb: assertion failure in VDec::VDec at /sql/sql_type.cc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "34",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: incorrect key in \"dup value\" error after long unique",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-03-16T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27457",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27457",
						"Description": "CVE-2022-27457"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075699",
						"Description": "bz#2075699: CVE-2022-27457 mariadb: incorrect key in \"dup value\" error after long unique"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "35",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: use-after-poison in Binary_string::free_buffer",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-11-09T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-27458",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-27458",
						"Description": "CVE-2022-27458"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2075700",
						"Description": "bz#2075700: CVE-2022-27458 mariadb: use-after-poison in Binary_string::free_buffer"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-04-14T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "36",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-09-07T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-31622",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-31622",
						"Description": "CVE-2022-31622"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2092354",
						"Description": "bz#2092354: CVE-2022-31622 mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-06-01T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "37",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-09-07T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-31623",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n\nAfter installing this update, the MySQL server daemon (mysqld) will be restarted automatically. After installing this update, the MariaDB server daemon (mysqld) will be restarted automatically.\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:5948"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-31623",
						"Description": "CVE-2022-31623"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2092360",
						"Description": "bz#2092360: CVE-2022-31623 mariadb: improper locking due to the unreleased lock in extra/mariabackup/ds_compress.cc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-06-01T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
						"AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
						"CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat Enterprise Linux",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux AppStream (v. 9)",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux AppStream (v. 9)",
							"productid": "AppStream-9.0.0.Z.MAIN.EUS",
							"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat CodeReady Linux Builder (v. 9)",
						"fullproductname": {
							"text": "Red Hat CodeReady Linux Builder (v. 9)",
							"productid": "CRB-9.0.0.Z.MAIN.EUS",
							"cpe": "cpe:/a:redhat:enterprise_linux:9::crb"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "galera-0:26.4.11-1.el9_0",
				"fullproductname": {
					"text": "galera-26.4.11-1.el9_0.src.rpm",
					"productid": "galera-0:26.4.11-1.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			},
			{
				"type": "Product Version",
				"name": "mariadb-3:10.5.16-2.el9_0",
				"fullproductname": {
					"text": "mariadb-10.5.16-2.el9_0.src.rpm",
					"productid": "mariadb-3:10.5.16-2.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			},
			{
				"type": "Product Version",
				"name": "mysql-selinux-0:1.0.5-1.el9_0",
				"fullproductname": {
					"text": "mysql-selinux-1.0.5-1.el9_0.src.rpm",
					"productid": "mysql-selinux-0:1.0.5-1.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			}
		],
		"relationship": [
			{
				"productreference": "galera-0:26.4.11-1.el9_0",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "AppStream-9.0.0.Z.MAIN.EUS",
				"fullproductname": {
					"text": "galera-0:26.4.11-1.el9_0 as a component of Red Hat Enterprise Linux AppStream (v. 9)",
					"productid": "AppStream-9.0.0.Z.MAIN.EUS:galera-0:26.4.11-1.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			},
			{
				"productreference": "mariadb-3:10.5.16-2.el9_0",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "AppStream-9.0.0.Z.MAIN.EUS",
				"fullproductname": {
					"text": "mariadb-3:10.5.16-2.el9_0 as a component of Red Hat Enterprise Linux AppStream (v. 9)",
					"productid": "AppStream-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			},
			{
				"productreference": "mysql-selinux-0:1.0.5-1.el9_0",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "AppStream-9.0.0.Z.MAIN.EUS",
				"fullproductname": {
					"text": "mysql-selinux-0:1.0.5-1.el9_0 as a component of Red Hat Enterprise Linux AppStream (v. 9)",
					"productid": "AppStream-9.0.0.Z.MAIN.EUS:mysql-selinux-0:1.0.5-1.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::appstream"
				}
			},
			{
				"productreference": "mariadb-3:10.5.16-2.el9_0",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "CRB-9.0.0.Z.MAIN.EUS",
				"fullproductname": {
					"text": "mariadb-3:10.5.16-2.el9_0 as a component of Red Hat CodeReady Linux Builder (v. 9)",
					"productid": "CRB-9.0.0.Z.MAIN.EUS:mariadb-3:10.5.16-2.el9_0",
					"cpe": "cpe:/a:redhat:enterprise_linux:9::crb"
				}
			}
		]
	}
}
