{
	"documenttitle": {
		"text": "Red Hat Security Advisory: Red Hat OpenStack Platform 16.1 (python-django20) security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2021:5070"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2021-12-09T20:20:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2021-12-09T20:20:00Z",
		"CurrentReleaseDate": "2021-12-09T20:20:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.3.0",
			"Date": "2021-12-10T03:00:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for python-django20 is now available for Red Hat OpenStack\nPlatform 16.1 (Train).\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nSecurity Fix(es):\n\n* Potential directory-traversal via archive.extract() (CVE-2021-3281)\n\n* potential directory-traversal via uploaded files (CVE-2021-28658)\n\n* Potential directory-traversal via uploaded files (CVE-2021-31542)\n\n* Potential directory traversal via ``admindocs`` (CVE-2021-33203)\n\n* Possible indeterminate SSRF RFI and LFI attacks since validators accepted\nleading zeros in IPv4 addresses (CVE-2021-33571)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2021 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2021:5070",
				"Description": "https://access.redhat.com/errata/RHSA-2021:5070"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Potential directory-traversal via archive.extract()",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-02-01T10:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-3281",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:5070"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-3281",
						"Description": "CVE-2021-3281"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1919969",
						"Description": "bz#1919969: CVE-2021-3281 django: Potential directory-traversal via archive.extract()"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-01-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: potential directory-traversal via uploaded files",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-06T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-28658",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:5070"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2021/apr/06/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2021/apr/06/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-28658",
						"Description": "CVE-2021-28658"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1944801",
						"Description": "bz#1944801: CVE-2021-28658 django: potential directory-traversal via uploaded files"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-03-30T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Potential directory-traversal via uploaded files",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-05-04T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-31542",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:5070"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2021/may/04/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2021/may/04/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-31542",
						"Description": "CVE-2021-31542"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1954294",
						"Description": "bz#1954294: CVE-2021-31542 django: Potential directory-traversal via uploaded files"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-04-27T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "4",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Potential directory traversal via ``admindocs``",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-06-02T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-33203",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:5070"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-33203",
						"Description": "CVE-2021-33203"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1966251",
						"Description": "bz#1966251: CVE-2021-33203 django: Potential directory traversal via ``admindocs``"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-05-26T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "5",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-06-02T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-33571",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:5070"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-33571",
						"Description": "CVE-2021-33571"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1966253",
						"Description": "bz#1966253: CVE-2021-33571 django: Possible indeterminate SSRF, RFI, and LFI attacks since validators accepted leading zeros in IPv4 addresses"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-05-26T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat OpenStack Platform",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat OpenStack Platform 16.1",
						"fullproductname": {
							"text": "Red Hat OpenStack Platform 16.1",
							"productid": "8Base-RHOS-16.1",
							"cpe": "cpe:/a:redhat:openstack:16.1::el8"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python-django20-0:2.0.13-16.el8ost.1",
				"fullproductname": {
					"text": "python-django20-2.0.13-16.el8ost.1.src.rpm",
					"productid": "python-django20-0:2.0.13-16.el8ost.1",
					"cpe": "cpe:/a:redhat:openstack:16.1::el8"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python-django20-0:2.0.13-16.el8ost.1",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "8Base-RHOS-16.1",
				"fullproductname": {
					"text": "python-django20-0:2.0.13-16.el8ost.1 as a component of Red Hat OpenStack Platform 16.1",
					"productid": "8Base-RHOS-16.1:python-django20-0:2.0.13-16.el8ost.1",
					"cpe": "cpe:/a:redhat:openstack:16.1::el8"
				}
			}
		]
	}
}
