{
	"documenttitle": {
		"text": "Red Hat Security Advisory: python38:3.8 and python38-devel:3.8 security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2021:4162"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2021-12-23T21:28:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2021-11-09T17:54:00Z",
		"CurrentReleaseDate": "2021-12-23T21:28:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.3.0",
			"Date": "2021-12-26T21:00:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for the python38:3.8 and python38-devel:3.8 modules is now available for Red Hat Enterprise Linux 8.\n\nRed Hat Product Security has rated this update as having a security impact of Moderate. A Common Vulnerability Scoring System (CVSS) base score, which gives a detailed severity rating, is available for each vulnerability from the CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nPython is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems. \n\nSecurity Fix(es):\n\n* python-psutil: Double free because of refcount mishandling (CVE-2019-18874)\n\n* python-jinja2: ReDoS vulnerability in the urlize filter (CVE-2020-28493)\n\n* python: Information disclosure via pydoc (CVE-2021-3426)\n\n* python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code (CVE-2021-20095, CVE-2021-42771)\n\n* python: Web cache poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a semicolon in query parameters (CVE-2021-23336)\n\n* python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS (CVE-2021-28957)\n\n* python-ipaddress: Improper input validation of octal strings (CVE-2021-29921)\n\n* python-urllib3: ReDoS in the parsing of authority part of URL (CVE-2021-33503)\n\n* python-pip: Incorrect handling of unicode separators in git references (CVE-2021-3572)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.5 Release Notes linked from the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2021 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2021:4162",
				"Description": "https://access.redhat.com/errata/RHSA-2021:4162"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/",
				"Description": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-psutil: Double free because of refcount mishandling",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-11-07T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-18874",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-18874",
						"Description": "CVE-2019-18874"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1772014",
						"Description": "bz#1772014: CVE-2019-18874 python-psutil: Double free because of refcount mishandling"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-11-13T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "This issue was discovered by Riccardo Schirone (Red Hat)."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Unsafe use of eval() on data retrieved via HTTP in the test suite",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2020-10-05T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2020-27619",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2020-27619",
						"Description": "CVE-2020-27619"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1889886",
						"Description": "bz#1889886: CVE-2020-27619 python: Unsafe use of eval() on data retrieved via HTTP in the test suite"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2020-10-08T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-jinja2: ReDoS vulnerability in the urlize filter",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-02-01T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2020-28493",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2020-28493",
						"Description": "CVE-2020-28493"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1928707",
						"Description": "bz#1928707: CVE-2020-28493 python-jinja2: ReDoS vulnerability in the urlize filter"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-02-15T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "4",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Information disclosure via pydoc",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-03-10T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-3426",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-3426",
						"Description": "CVE-2021-3426"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1935913",
						"Description": "bz#1935913: CVE-2021-3426 python: Information disclosure via pydoc"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-01-19T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank David SchwÃ¶rer (Fedora) for reporting this issue."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "5",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-pip: Incorrect handling of unicode separators in git references",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-24T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-3572",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-3572",
						"Description": "CVE-2021-3572"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1962856",
						"Description": "bz#1962856: CVE-2021-3572 python-pip: Incorrect handling of unicode separators in git references"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Low"
				}
			},
			"DiscoveryDate": "2021-05-19T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "6",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-28T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-20095",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.tenable.com/security/research/tra-2021-14",
						"Description": "https://www.tenable.com/security/research/tra-2021-14"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-20095",
						"Description": "CVE-2021-20095"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1955615",
						"Description": "bz#1955615: CVE-2021-20095 CVE-2021-42771 python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-04-29T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "7",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python: Web cache poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a semicolon in query parameters",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-02-13T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-23336",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933",
						"Description": "https://snyk.io/vuln/SNYK-UPSTREAM-PYTHONCPYTHON-1074933"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-23336",
						"Description": "CVE-2021-23336"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1928904",
						"Description": "bz#1928904: CVE-2021-23336 python: Web cache poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a semicolon in query parameters"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-02-15T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "8",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-03-21T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-28957",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-28957",
						"Description": "CVE-2021-28957"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1941534",
						"Description": "bz#1941534: CVE-2021-28957 python-lxml: Missing input sanitization for formaction HTML5 attributes may lead to XSS"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-03-21T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "9",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-ipaddress: Improper input validation of octal strings",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-30T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-29921",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html",
						"Description": "https://python-security.readthedocs.io/vuln/ipaddress-ipv4-leading-zeros.html"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-29921",
						"Description": "CVE-2021-29921"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1957458",
						"Description": "bz#1957458: CVE-2021-29921 python-ipaddress: Improper input validation of octal strings"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-04-30T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "10",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-urllib3: ReDoS in the parsing of authority part of URL",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-06-01T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-33503",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg",
						"Description": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-33503",
						"Description": "CVE-2021-33503"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1968074",
						"Description": "bz#1968074: CVE-2021-33503 python-urllib3: ReDoS in the parsing of authority part of URL"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-06-01T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "11",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2021-04-28T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2021-42771",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes described in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2021:4162"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.tenable.com/security/research/tra-2021-14",
						"Description": "https://www.tenable.com/security/research/tra-2021-14"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2021-42771",
						"Description": "CVE-2021-42771"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1955615",
						"Description": "bz#1955615: CVE-2021-20095 CVE-2021-42771 python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2021-04-29T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
						"CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat Enterprise Linux",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux AppStream (v. 8)",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux AppStream (v. 8)",
							"productid": "AppStream-8.5.0.GA",
							"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat CodeReady Linux Builder (v. 8)",
						"fullproductname": {
							"text": "Red Hat CodeReady Linux Builder (v. 8)",
							"productid": "CRB-8.5.0.GA",
							"cpe": "cpe:/a:redhat:enterprise_linux:8::crb"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python38-devel:3.8-8050020210811101222.e3d35cca",
				"fullproductname": {
					"text": "python38-devel-3.8-8050020210811101222.e3d35cca",
					"productid": "python38-devel:3.8-8050020210811101222.e3d35cca",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::crb"
				}
			},
			{
				"type": "Product Version",
				"name": "python38:3.8-8050020210811101222.e3d35cca",
				"fullproductname": {
					"text": "python38-3.8-8050020210811101222.e3d35cca",
					"productid": "python38:3.8-8050020210811101222.e3d35cca",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python38:3.8-8050020210811101222.e3d35cca",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "AppStream-8.5.0.GA",
				"fullproductname": {
					"text": "python38:3.8-8050020210811101222.e3d35cca as a component of Red Hat Enterprise Linux AppStream (v. 8)",
					"productid": "AppStream-8.5.0.GA:python38:3.8-8050020210811101222.e3d35cca",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::appstream"
				}
			},
			{
				"productreference": "python38-devel:3.8-8050020210811101222.e3d35cca",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "CRB-8.5.0.GA",
				"fullproductname": {
					"text": "python38-devel:3.8-8050020210811101222.e3d35cca as a component of Red Hat CodeReady Linux Builder (v. 8)",
					"productid": "CRB-8.5.0.GA:python38-devel:3.8-8050020210811101222.e3d35cca",
					"cpe": "cpe:/a:redhat:enterprise_linux:8::crb"
				}
			}
		]
	}
}
