{
	"documenttitle": {
		"text": "Red Hat Security Advisory: python-glanceclient security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2013:1200"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2013-09-03T20:16:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2013-09-03T20:16:00Z",
		"CurrentReleaseDate": "2013-09-03T20:16:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.0.0",
			"Date": "2021-08-23T04:35:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn updated python-glanceclient package that fixes one security issue is now\navailable for Red Hat OpenStack 3.0.\n\nThe Red Hat Security Response Team has rated this update as having moderate\nsecurity impact. A Common Vulnerability Scoring System (CVSS) base score,\nwhich gives a detailed severity rating, is available from the CVE link in\nthe References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nThe python-glanceclient package provides a client for the OpenStack Glance\nAPI.\n\nIt was discovered that the Python Glance client did not properly check\nSSL certificates. An attacker could use this flaw to conduct\nman-in-the-middle attacks. (CVE-2013-4111)\n\nRed Hat would like to thank the OpenStack project for reporting this issue.\nUpstream acknowledges Thomas Leaman of HP as the original reporter.\n\nAll users of python-glanceclient are advised to upgrade to this updated\npackage, which corrects this issue.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2021 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2013:1200",
				"Description": "https://access.redhat.com/errata/RHSA-2013:1200"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "OpenStack: python-glanceclient failing SSL certificate check",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2013-07-29T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2013-4111",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nBefore applying this update, make sure all previously released errata\nrelevant to your system have been applied.\n\nThis update is available via the Red Hat Network. Details on how to\nuse the Red Hat Network to apply this update are available at\nhttps://access.redhat.com/site/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2013:1200"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2013-4111",
						"Description": "CVE-2013-4111"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=989738",
						"Description": "bz#989738: CVE-2013-4111 OpenStack: python-glanceclient failing SSL certificate check"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2013-07-29T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"6Server-Grizzly:python-glanceclient-1:0.9.0-2.el6ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "5.0",
					"Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N"
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat OpenStack Platform",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat Enterprise Linux OpenStack Platform 3.0",
						"fullproductname": {
							"text": "Red Hat Enterprise Linux OpenStack Platform 3.0",
							"productid": "6Server-Grizzly",
							"cpe": "cpe:/a:redhat:openstack:3::el6"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python-glanceclient-1:0.9.0-2.el6ost",
				"fullproductname": {
					"text": "python-glanceclient-0.9.0-2.el6ost.src.rpm",
					"productid": "python-glanceclient-1:0.9.0-2.el6ost",
					"cpe": "cpe:/a:redhat:openstack:3::el6"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python-glanceclient-1:0.9.0-2.el6ost",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "6Server-Grizzly",
				"fullproductname": {
					"text": "python-glanceclient-1:0.9.0-2.el6ost as a component of Red Hat Enterprise Linux OpenStack Platform 3.0",
					"productid": "6Server-Grizzly:python-glanceclient-1:0.9.0-2.el6ost",
					"cpe": "cpe:/a:redhat:openstack:3::el6"
				}
			}
		]
	}
}
